services:

  car-detection-service:
    build:
      context: ./car-detection-service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  data-management-service:
    build:
      context: ./data-management-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  alert-management-service:
    build:
      context: ./alert-management-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb


  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mydatabase'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

